import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div className="app-container flex justify-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel='preconnect' href="https://fonts.gstatic.com"/>
        <link href="https://fonts.googleapis.com/css2?family=Comic+Neue:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&display=swap" rel="stylesheet"></link>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="xl:text-9xl">Hello, Wisper</h1>
      </main>
    </div>
  )
}
