import Axios from "axios";
import Head from "next/head";

//const fetcher = (url) => Axios.get(url).then((res) => res.data);

export default function Home(props) {
  // const { data,error } = useSWR('http://127.0.0.1:3080/api/user/info',fetcher)

  // if (error) return <div className="app-container text-center text-9xl">^_^</div>
  // if (!data) return <div className="app-container text-center text-9xl">Loading...</div>

  // const userinfo = data
  return (
    <div className="app-container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link href="/fonts/font.css" rel="stylesheet"></link>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div
          className="absolute p-4 text-sm text-left text-white"
          style={{ background: "#D5314D00", borderRadius: 15 + "px" }}
        >
          <blockquote>
            <pre>
              <div>
                <p style={{ fontFamily: "'Times New Roman',Georgia,Serif" }}>
                  {" ╭╴                                              ╶╮"}
                </p>
                <p id="realtime" className="ml-6">
                  <script src="/js/timer.js"></script>
                </p>
                <p style={{ fontFamily: "'Times New Roman',Georgia,Serif" }}>
                  {" ╰╴                                              ╶╯"}
                </p>
              </div>
              <div className="text-sm">
                <span>
                  {"\n"}
                  <span>2021/5/12 下午3:15</span>
                  {"\t"}|{"\t"}
                  <span>提交毕业设计</span>
                  {"\t"}|{"\t"}
                  <span>论文查重</span>
                </span>
                <span>
                  {"\n"}
                  <span>2021/5/10 下午3:15</span>
                  {"\t"}|{"\t"}
                  <span>接种疫苗</span>
                  {"\t"}|{"\t"}
                  <span>学生中心</span>
                </span>
                <br />
              </div>
            </pre>
          </blockquote>
        </div>
      </main>
    </div>
  );
}
